# Generated by Django 5.0.6 on 2024-06-19 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_book_alter_customuser_managers_customuser_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='public_visibility',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(upload_to='covers/'),
        ),
    ]
