# Generated by Django 5.0.6 on 2024-06-20 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_book_public_visibility_alter_book_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='uploader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='book',
            name='public_visibility',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='public_visibility',
            field=models.BooleanField(default=False),
        ),
    ]
