# Generated by Django 4.1.6 on 2023-02-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_city_customuser_credit_num_customuser_cvc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('cover', models.ImageField(upload_to='cover/')),
                ('pdf', models.FileField(upload_to='pdf/')),
            ],
        ),
    ]
