# Generated by Django 4.1.6 on 2023-02-14 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
